/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "haptic": {
    name: "haptic",
    description: "Trigger haptic feedback on mobile devices.",
    type: "registry:lib",
    files: [{
      path: "src/registry/lib/haptic/haptic.ts",
      type: "registry:lib",
      target: "@lib/haptic.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/haptic/haptic.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "text-flip": {
    name: "text-flip",
    description: "Animated text that cycles through items with a smooth flip transition.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/text-flip/text-flip.tsx",
      type: "registry:component",
      target: "@components/text-flip.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/text-flip/text-flip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["text-effects"],
    meta: undefined,
  },
  "chevrons-up-down-icon": {
    name: "chevrons-up-down-icon",
    description: "Animated chevrons icon that morphs between up and down directions.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx",
      type: "registry:component",
      target: "@components/chevrons-up-down-icon.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/chevrons-up-down-icon/chevrons-up-down-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "Copy text to clipboard with visual, haptic, and audio feedback.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/copy-button/copy-button.tsx",
      type: "registry:component",
      target: "@components/copy-button.tsx",
    },{
      path: "src/hooks/use-copy-to-clipboard.ts",
      type: "registry:hook",
      target: "@hooks/use-copy-to-clipboard.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/copy-button/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["utilities"],
    meta: undefined,
  },
  "middle-truncation": {
    name: "middle-truncation",
    description: "Truncate text in the middle while preserving start and end.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/middle-truncation/middle-truncation.tsx",
      type: "registry:component",
      target: "@components/middle-truncation.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/middle-truncation/middle-truncation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["typography"],
    meta: undefined,
  },
  "contribution-graph": {
    name: "contribution-graph",
    description: "A GitHub-style contribution graph component that displays activity levels over time.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/contribution-graph/contribution-graph.tsx",
      type: "registry:component",
      target: "@components/contribution-graph.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/contribution-graph/contribution-graph.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "github-contributions": {
    name: "github-contributions",
    description: "Visualize year-long GitHub contribution activity with daily counts, tooltips, and a profile link.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/github-contributions/github-contributions.tsx",
      type: "registry:component",
      target: "@components/github-contributions.tsx",
    },{
      path: "src/registry/transformed/components/github-contributions/lib/get-cached-contributions.ts",
      type: "registry:lib",
      target: "@lib/get-cached-contributions.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/github-contributions/github-contributions.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["data-display"],
    meta: undefined,
  },
  "icon-swap": {
    name: "icon-swap",
    description: "Animate icon swaps with scale, blur, and fade transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/icon-swap/icon-swap.tsx",
      type: "registry:component",
      target: "@components/icon-swap.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/icon-swap/icon-swap.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "dot-grid-spotlight": {
    name: "dot-grid-spotlight",
    description: "Interactive dot grid with a cursor-tracking spotlight effect.",
    type: "registry:component",
    files: [{
      path: "src/registry/transformed/components/dot-grid-spotlight/dot-grid-spotlight.tsx",
      type: "registry:component",
      target: "@components/dot-grid-spotlight.tsx",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/transformed/components/dot-grid-spotlight/dot-grid-spotlight.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["effects"],
    meta: undefined,
  },
  "text-flip-demo": {
    name: "text-flip-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/text-flip-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/text-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/copy-button-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/copy-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "haptic-demo": {
    name: "haptic-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/haptic-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/haptic-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "middle-truncation-demo": {
    name: "middle-truncation-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/middle-truncation-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/middle-truncation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-demo": {
    name: "github-contributions-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-default-theme": {
    name: "github-contributions-default-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-default-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-default-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-winter-theme": {
    name: "github-contributions-winter-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-winter-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-winter-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "github-contributions-halloween-theme": {
    name: "github-contributions-halloween-theme",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/github-contributions-halloween-theme.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/github-contributions-halloween-theme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "icon-swap-demo": {
    name: "icon-swap-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/icon-swap-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/icon-swap-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dot-grid-spotlight-demo": {
    name: "dot-grid-spotlight-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/dot-grid-spotlight-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/dot-grid-spotlight-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "chevrons-up-down-icon-demo": {
    name: "chevrons-up-down-icon-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/chevrons-up-down-icon-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/chevrons-up-down-icon-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}